### ISSUE TITLE
Implement markup for parameter block

### ISSUE THREAD

**Issue by davojta** [opendataby/city-dashboard#11]
take https://dashboard.edmonton.ca/ as example

![parameter block](http://i.imgur.com/HVx8u4k.png)

We have the following attributes for params
- param info icon (maybe font awesome will be enough)
- param title
- param dimension

markup should be placed to https://github.com/opendataby/city-dashboard/blob/master/index.html#L25

**Comment by gsk990** [comment]
looks awesome, thank you, Mariya!
