### ISSUE TITLE
Исследование анализа датасета парковок из осма

### ISSUE THREAD

**Issue by Hello-Vsevolod** [opendataby/city-dashboard#14]

**Comment by tbicr** [comment]
Hi, can I help you with it? What info you need?

**Comment by gsk990** [comment]
Павел - спасибо, мы со Всеволодом на смарт-сити хакатоне пытались
разобраться, как из ОСМ получить а) количество парковок б) парковочных мест
по районам Минска.

пока нашли вот этот результат брэйншторминга, но там всё запутанно. Как
можно попроще описать последовательность шагов?

https://github.com/opendataby/city-dashboard/blob/master/docs/city-parking.md

https://github.com/opendataby/city-dashboard/issues/10

P.S. есть такая цифра, может пригодиться - размеры парковочного места
2.3*4.18м

**Comment by tbicr** [comment]
1. па плошчавым amenity:parking ёсьць падзяленьне на surface і multi-storey калі ўлічваць праезды, то атрымаецца прыкладная колькасьць месцаў.
2. уздоўж вуліцы пазначана мала, таму больш калі ведаеш дзе стаяць, дзе не, таксама можна падлічыць, але гэта больш падыходзіць для невялічкіх раёнаў, якія ведаеш.
3. і пакуль нямае ідэі як падзяліць дваравыя і бізнэсовыя паркоўкі, таксама эмпірычна.

**Comment by tbicr** [comment]
1. па плошчавым amenity:parking ёсьць падзяленьне на surface і multi-storey калі ўлічваць праезды, то атрымаецца прыкладная колькасьць месцаў.
2. уздоўж вуліцы пазначана мала, таму больш калі ведаеш дзе стаяць, дзе не, таксама можна падлічыць, але гэта больш падыходзіць для невялічкіх раёнаў, якія ведаеш.
3. і пакуль нямае ідэі як падзяліць дваравыя і бізнэсовыя паркоўкі, таксама эмпірычна.

**Comment by davojta** [comment]
Это закрываю, как задачу с хакатона
