### ISSUE TITLE
Добавить под каждым индикатором текст на 1 строкe с пояснением

### ISSUE THREAD

**Issue by gsk990** [opendataby/city-dashboard#20]
пример - https://dashboard.edmonton.ca/green

название индикатора: Missed waste collection stops (Незабранные мусорные контейнеры)
value: 5
пояснение: per 10 000 collection stops (в расчёте на 10 000 остановок мусоровоза)

У нас есть тоже индикаторы, которые рассчитываются на 10 000 человек, но непонятно, где это пояснение добавить.

Если будет время добавить, то будем очень благодарны!

**Comment by davojta** [comment]
Данный параметр надо добавлять в https://github.com/opendataby/city-dashboard/blob/master/data/frontend.json поле размерность "unit": "Максимальное превышение за неделю"

выглядит так 
![screenshot_20161205_213843](https://cloud.githubusercontent.com/assets/893650/20897407/3d934a0e-bb33-11e6-898a-f167b4a4ecf6.png)

**Comment by davojta** [comment]
данный тикет будет решен в рамках https://github.com/opendataby/city-dashboard/issues/24 и https://github.com/opendataby/city-dashboard/issues/23
