### ISSUE TITLE
Прыкруціць сайту дамен

### ISSUE THREAD

**Issue by gsk990** [opendataby/city-dashboard#45]
замест 
https://opendataby.github.io/city-dashboard/
зрабіць city.opendata.by

https://help.github.com/articles/using-a-custom-domain-with-github-pages/

**Comment by abitrolly** [comment]
ня ведаю хто, але ж верагодна @ushchent усё зрабiу тры гады таму - https://github.com/opendataby/city-dashboard/commits/master/CNAME
