### ISSUE TITLE
[главный экран: индикатор качество воды] Подготовить список водозаборных станций в Минске

### ISSUE THREAD

**Issue by radachynskaja** [opendataby/city-dashboard#51]

**Comment by radachynskaja** [comment]
11 водозаборов артезианских источников, объединяющих 18 насосных станций 2-го подъема, распложенных как в черте города, так и за его пределами
1) водозабор №1 "Новинки" ("Новинки", "Психбольница", "Масюковщина" )
2) №2 "Петровщина"
3) №3 "Зеленовка" ("Зеленовка", "Уручье", "Рогачевская")
4) №4 "Дражня" ("Дражня", "Колядичи", "Сосны")
5) №5 "Боровляны"
6) №6 "Островы"
7) №7 "Волма"
8) №8 "Вицковщина"
9) №9 "Водопой"
10) №10 "Фелицианово"
11) №11 "Зеленый Бор", ВКХ "Сокол"
12) станция, подающая воду из поверхностного источника, - очистная водопроводная станция (ОВС)

**Comment by radachynskaja** [comment]
І чутка дадатковай інфы пра ачыстку: 
Вода из артезианских источников преимущественно подается потребителям без дополнительной очистки и обработки хлором. Однако, некоторые водоносные горизонты характеризуются повышенным содержанием железа и марганца. Особенно это характерно для водоностных горизонтов, питающих водозаборы №2 "Петровщина", №6 "Островы", №8 "Вицковщина", №9 "Водопой", №10 "Фелицианово". Вода с этих водозаборов поступает на станции обезжелезивания (СОЖ), расположенные на площадках насосных станций, где подвергается аэрации и фильтрованию, что позволяет снизить остаточную концентрацию железа и марганца в воде на подаче потребителям до 0,1 мг/дм3. 
Вода из поверхностного источника (поверхностный источник водоснабжения)
Вода из поверхностного источника, резервного водохранилища "Крылово", расположенного около д.Вишневка Минского района, по трем гравитационным водоводам диаметром 1 400 мм поступает на очистную водопроводную станцию (ОВС), где проходит очистку перед подачей в водопроводную сеть.

**Comment by radachynskaja** [comment]
крыніца інфы: http://minskvodokanal.by/about/activities/water-supply/

**Comment by ushchent** [comment]
Подскажите, пжл., доступен ли еще xls-файл с исходными данными по качеству воды на http://minskvodokanal.by? Он раньше публиковался, а сейчас там сервис с картой http://minskvodokanal.by/water/home/.

**Comment by radachynskaja** [comment]
- адзначыць у індыкатары паказчык натуральнай мінералізацыі

**Comment by abitrolly** [comment]
@ushchent http://minskvodokanal.by/assets/files/Excel/kachestvovody.xlsx и вообще http://minskvodokanal.by/assets/files/Excel/ =)

**Comment by abitrolly** [comment]
За 4.3 рубля можно похавать нормально. =)

![kompl2](https://cloud.githubusercontent.com/assets/8781107/24580375/b6eaa342-170f-11e7-87cb-0855d7181cba.jpg)

**Comment by ushchent** [comment]
@abitrolly ну так это же январские данные. Хотя, файл в последний раз менялся в марте. Короче, нужно выяснять.

**Comment by radachynskaja** [comment]
@ushchent кажется, нет, во всяком случае мы не нашли. а ты работал с ним раньше? может, стоит им написать о нем?

**Comment by ushchent** [comment]
Про данные о качестве воды - https://groups.google.com/d/msg/opendata-belarus/F_0VXkcFAnM/8Zyq2uWNFgAJ

**Comment by gsk990** [comment]
оказывается, Алексей Медвецкий даавно уже распарсил и выложил список станций и сами данные по качеству воды! 
alexey medvetsky <a.medvetsky@gmail.com>
11/8/16

to opendata-belar. 
Вот http://bezvody.opendata.by/data/data_voda.csv, только там 3 станции не удалось геокодировать ЛПНС Степянка, н/ст Уручье и н/ст II-го подъема в/з Дражня (ул. Солтыса). Наверное, придется выезжать с локатором. :)


вот cписок с координатами:
station	address	lon	lat
РПНС Зеленый Луг	улица Карбышева, 9/2	27.633184	53.952804
РПНС Филимонова	улица Филимонова, 53а	27.631486	53.923578
РПНС Кульман	улица Кульман, 65а	27.576267	53.92388
РПНС Некрасова	улица Беды, 19а	27.588942	53.9325
РПНС Цнянская	улица Цнянская, 14	27.585834	53.924903
РПНС Аэродромная	улица Жуковского, 10 к.3	27.547404	53.880592
РПНС Курасовщина-1	улица Корженевского, 4б	27.49797	53.84544
РПНС Курасовщина-3	улица Кижеватова, 60а	27.530642	53.850082
РПНС Дружба	улица Н.Орды, 20	27.487738	53.845737
РПНС Запад	улица Одинцова, 12а	27.45574	53.89979
РПНС Каменная горка	улица Неманская, 22	27.430776	53.910437
РПНС Красный бор	улица Одинцова, 105в	27.428341	53.899244
РПНС Кунцевщина	улица Лещинского, 21а	27.44646	53.911169
РПНС Веснянка	проспект Победителей, 87	27.504788	53.932426
РПНС Танковая	улица М.Танка, 22	27.533893	53.90945
РПНС Ангарская-2	улица Байкальская, 41	27.686993	53.87024
РПНС Ангарская-3	улица Герасименко, 49а	27.680292	53.884493
РПНС Шабаны	улица Бачило, 22	27.701097	53.843501
РПНС Лошица	улица Сырокомли, 11	27.55804	53.844361
РПНС Серебрянка	проспект Рокоссовского, 12/2	27.594431	53.871727

**Comment by gsk990** [comment]
мапа горада са станцыямі:
bezvody.opendata.by/voda.html
