### ISSUE TITLE
[главный экран: индикатор качества ЖКХ]: распарсить архив заявок 115.бел 

### ISSUE THREAD

**Issue by radachynskaja** [opendataby/city-dashboard#53]
1. Категория
2. Подкатегория
3. Автор
4. Дата (когда открыта)
5. Адрас
6. Название заявки
7. Статус
8. Дата (когда решена)

**Comment by radachynskaja** [comment]
тэхналогія scrapy, scrapinghub

**Comment by gsk990** [comment]
адрас АРІ на 115.бел

Request URL:http://115.xn--90ais/api/problem/getlist
Request Method:POST
делаем пост запрос по этому урлу, получаем 3.7 мегабайта json
внутри все заявки.

Наколькі складана было б скачаць архіў з гэтым json каб паспрабаваць яго апрацаваць/імпартаваць у друпал, напрыклад, для геакодзінга і сарціроўкі па катэгорыях?

**Comment by abitrolly** [comment]
Ошмётки кода https://github.com/opendataby/tools/tree/gh-pages/scrapers - надо мне приоритет выставить, чтобы довести до ума.

**Comment by abitrolly** [comment]
Надо отдельную метку на парсинг. `coding` - слишком в общем звучит.

**Comment by abitrolly** [comment]
* [ ] надо со статусами разобраться - они номерами идут 1 3 4 5 7, что непонятно

**Comment by abitrolly** [comment]
* [ ] названия заявки на карте нет, надо отдельно вытягивать по номеру

**Comment by abitrolly** [comment]
* [ ] поля когда решена я тоже не вижу в данных, если поле `planned`

**Comment by abitrolly** [comment]
Проверяйте.

[dataset-115.бел-2017-04-03.zip](https://github.com/opendataby/city-dashboard/files/894073/dataset-115.-2017-04-03.zip)

**Comment by gsk990** [comment]
ответы по результатам лабы:
 со статусами разобраться 
 1 3 4 5 7
3,Отклонено
4,В работе
5,Решено
7,На контроле

**Comment by gsk990** [comment]
ИндексКатегории,НазваниеКатегории
6,Дворовые территории | Благоустройство территории
7,Дворовые территории | Санитарное состояние
9,Многоквартирные дома | Общие проблемы, неисправности, повреждения
10,Многоквартирные дома | Электроработы
11,Многоквартирные дома | Общестроительные работы
12,Многоквартирные дома | Текущий ремонт жилфонда за счет средств плательщиков
13,Многоквартирные дома | Неисправность лифта
14,Многоквартирные дома | Санитарное состояние
20,Инфраструктура города | Дороги, тротуары
21,Инфраструктура города | Парки, скверы
22,Инфраструктура города | Рекламные и информационные конструкции
23,Инфраструктура города | Общественный транспорт, остановки общественного транспорта

6.371,Отсутствие дворового освещения,
6.26,Наличие выбоин и ям на проезжей части двора,
6.27,Обрезка, посадка, и снос деревьев и кустарников,
6.28,Состояние площадок для выгула домашних животных,
6.29,Содержание и техническое состояние оборудования детской площадки,
6.30,Наличие и техническое состояние скамеек, урн, цветочниц, беседок и др.
6.33,Техническое состояние контейнеров для сбора отходов,
6.34,состояние ограждения контейнерной площадки,
6.36,Содержание пешеходных лестниц,
6.37,Техническое  состояние покрытий пешеходных дорожек, парковок
6.38,Содержание песочниц и наличие в них песка,
6.324,Требуется ремонт (установка) ограждения,
6.370,Наличие просадки грунта вокруг технических колодцев,
6.325,Иное/Дворовые территории | Благоустройство территории,
7.40,Не убрана дворовая территория,
7.41,Не вывезены контейнеры с твердыми коммунальными отходами,
7.42,Не убрана контейнерная площадка,
7.43,Не выполнена противогололедная обработка,
7.44,Наличие безнадзорных животных на территории,
7.45,Не вывезен крупногабаритный мусор,
7.46,Не скошен газон,
7.47,Не очищены урны,
7.48,Иное,
9.52,Несанкционированные объявления, надписи и рисунки на фасадах
9.53,Отсутствие/повреждение указателей с наименованием улицы и номером дома,
9.54,Протечка канализационных стоков на дворовую территорию, во вспомогательные помещения
9.55,Протечка воды на дворовую территорию, во вспомогательные помещения
9.56,Мусор на козырьке над входом в подъезд,
9.57,Иное,
9.58,Необходимость вывоза крупной и среднегабаритной бытовой техники,
10.61,Не закреплена электропроводка на лестничной клетке,
10.62,Открыт электрощиток
10.63,Отсутствие фасадного освещения
10.64,Постоянно горит свет в подъезде
10.65,Закрепление электропроводки в подвале
10.66,Иное/Многоквартирные дома | Электроработы
10.67,Отсутствие освещения в подъезде
11.94,Течь кровли
11.95,Открыт выход на кровлю / крышу
11.96,Открыто слуховое окно / люк
11.97,Оборваны или не закреплены водосточные трубы
11.98,Требуется ремонт отмостки
11.99,Повреждения лестничных ступеней
11.100,Повреждения входной двери в подъезд, подвал,
11.101,Течь стыков, промерзание стыков, промерзание стеновых панелей
11.102,Выветривание швов кирпичной кладки
11.103,Отслоение облицовочной плитки на фасаде дома
11.104,Наличие трещин на стене
11.105,Отсутствует решетка для очистки обуви на крыльце
11.106,Очистка желобов и свесов от грязи, растительности, наледи и сосулек
11.369,Иное
12.111,Требуется восстановление штукатурки и облицовки стен, потолков,
12.112,Выбоины, неровности , трещины стен и потолка
12.113,Повреждения лепных декоративных деталей подъездов.
12.114,Выбоины, трещины в полах,
12.115,Состояние покрытий полов
12.116,Состояние элементов мусоропроводов
12.117,Требуется окраска стен, потолков, трубопроводов
12.118,Иное
13.109,Поврежден корпус кабины лифта
13.137,Иное
13.138,Не работают кнопки управления лифтом
13.139,Отсутствует  (повреждена) кнопка вызова лифта
13.140,Отсутствует (недостаточное) освещение кабины лифта
13.141,Не освещена посадочная площадка
13.142,Лифт не работает
14.151,Не убраны от мусора вспомогательные помещения
14.152,Загромождение вспомогательных помещений
14.153,Наличие грызунов или насекомых
14.154,Не вымыты окна в подъезде
14.156,Иное
14.158,Прочистка засоров ствола мусоропровода
14.159,Мойка ствола и клапанов мусоропровода
20.280,Брошенный автомобиль на проезжей части
20.281,Неисправное освещение на проезжей части
20.282,Неисправный светофор
20.283,Некачественная укладка плитки на тротуаре
20.284,Некачественное содержание велодорожек
20.285,Неубранная проезжая часть/тротуар
20.286,Повреждение уличной лестницы
20.287,Нечитаемые/поврежденные/неправильно установленные дорожные знаки
20.288,Поврежденные дорожные ограждения
20.289,Поврежденные искусственные дорожные неровности
20.290,Подтопление проезжей части
20.291,Просадка люка/Незакрытый люк
20.292,Отсутсвует или повреждена дорожная разметка
20.293,Ямы/выступы на проезжей части/тротуаре
20.294,Неисправность/недоступность инфраструктуры для маломобильных граждан
20.295,Некачественное содержание подземных и надземных пешеходных переходов
20.296,Благоустройство улиц
20.297,Проблемы с гаражами / автостоянками / парковками
20.364,Иное
21.299,Неисправность освещения
21.300,Некачественное содержание велодорожек
21.301,Некачественное содержание инфраструктуры в парках / скверах
21.302,Иное,
21.303,Требуется посадка деревьев, кустарников
21.304,Необходим снос сухих и аварийных деревьев,
22.306,Ненадлежащее состояние рекламной конструкции,
22.307,Иное,
23.310,Грязь/мусор на остановках общественного транспорта,
23.311,Несанкционированные  надписи, изображения на остановках общественного транспорта
23.312,Отсутствие остановочных указателей маршрутов,
23.313,Отсутствие урны,
23.314,Повреждение остановки общественного транспорта,
23.315,Повреждение остановочных указателей маршрутов,
23.367,Иное,

**Comment by gsk990** [comment]
апублікавалі (з 2015 да 01.04.2017): https://opendata.by/dataset/1383/

дабавілі катэгорыі і статусы, плюс колькасць дзён вырашэння для кожнай заяўкі

**Comment by gsk990** [comment]
вот бы яшчэ і выкачваць гэта пастаянна :)

ітак, праблемы з гэтым датасэтам:
- няясна, як мы будзем яго абнаўляць. у ідэале, выкачваць кожны месяц і дабаўляць туды чалавечыя катэгорыі і падкатэгорыі замест нумароў катэгорый.
- няма адказаў ад ЖЭСа
- няма каардынатаў, трэба будзе паспрабаваць загеакодзіць па адрасах, каб разбіць на раёны і мікрараёны і пачаць рабіць аналітыку па раёнах

**Comment by abitrolly** [comment]
@gsk990 зрабіў новы праект пад парсер на https://github.com/opendataby/115 - дадавай туды гэтыя праблемы.
